* Minor: impr. maint. tasks

diff --git a/pistar-update b/pistar-update
--- a/pistar-update
+++ b/pistar-update
@@ -109,16 +109,17 @@ git_update() {
                         	env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${hwDeetz}] [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git fetch
                         	if [ "$(git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git diff --name-only origin/master 2>/dev/null | grep pistar-update 2>/dev/null)" = "pistar-update" ]; then
                                 	echo -e "\n[!] New version of the Updater available. Performing self-update..."
-                                	env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${hwDeetz}] [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git pull -q origin master &> /dev/null
-					if [ $? -ne 0 ]; then # reset bsin if pull fails
+					exit_status=$(env GIT_HTTP_CONNECT_TIMEOUT="10" GIT_HTTP_USER_AGENT="sbin-Checker $uaStr" git -C /usr/local/sbin --git-dir=/usr/local/sbin/.git pull origin master)
+					if [ $? -ne 0 ]; then # reset sbin if pull fails
+					    exit_status_message="$exit_status"
 					    if grep -q LOGNDROP /etc/iptables.rules; then
 						fwState="enabled"
 					    else
 						fwState="disabled"
 					    fi
-					    GIT_REPO=/usr/local/sbin
-					    rm -rf $GIT_REPO
-					    env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="BF_sbin-Reset ${uaStr}" git clone https://wpsd-swd.w0chp.net/WPSD-SWD/W0CHP-PiStar-sbin.git $GIT_REPO
+					    sbin_repo=/usr/local/sbin
+					    rm -rf $sbin_repo
+					    env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="BF_sbin-Reset [$exit_status_message] ${uaStr}" git clone https://wpsd-swd.w0chp.net/WPSD-SWD/W0CHP-PiStar-sbin.git $sbin_repo
 					    if [ "$fwState" == "enabled" ]; then
 						/usr/local/sbin/pistar-system-manager -efw
 					    else
