* Minor: code cleanups and comments

diff --git a/pistar-update b/pistar-update
--- a/pistar-update
+++ b/pistar-update
@@ -110,7 +110,7 @@ git_update() {
                         	if [ "$(git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git diff --name-only origin/master 2>/dev/null | grep pistar-update 2>/dev/null)" = "pistar-update" ]; then
                                 	echo -e "\n[!] New version of the Updater available. Performing self-update..."
                                 	env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${hwDeetz}] [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git pull -q origin master &> /dev/null
-					if [ $? -ne 0 ]; then
+					if [ $? -ne 0 ]; then # reset bsin if pull fails
 					    if grep -q LOGNDROP /etc/iptables.rules; then
 						fwState="enabled"
 					    else
