* Minor: cleanup legacy update funcs

diff --git a/pistar-update b/pistar-update
--- a/pistar-update
+++ b/pistar-update
@@ -134,20 +134,20 @@ git_update() {
 		fi
 		# Re-check that the updates are now good
 		if [[ $(git_checkUpdateRequired ${gitFolder}) -gt 0 ]]; then
-			if [[ ${gitFolder} == "/usr/local/sbin" ]]; then
-				rm -rf ${gitFolder}/pistar-upnp.service
-			fi
-			#echo "Updates were not successful, reverting to original files..."
-           		# W0CHP has more than one branch. So depending on what W0CHP branch the user has installed, pull that branch.
-           		if [[ ${gitFolder} == "/var/www/dashboard" ]]; then
-               			env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${hwDeetz}] [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git reset --hard origin/${dash_branch}
-           		else
-    	    			env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${hwDeetz}] [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git reset --hard origin/master
-			fi
+		    if [[ ${gitFolder} == "/usr/local/sbin" ]]; then
+			rm -rf ${gitFolder}/pistar-upnp.service
+		    fi
+		    # Updates were not successful, reverting to original files...
+		    # W0CHP has more than one branch. So depending on what W0CHP branch the user has installed, pull that branch.
+		    if [[ ${gitFolder} == "/var/www/dashboard" ]]; then
+			env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${hwDeetz}] [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git reset --hard origin/${dash_branch}
+		    else
+			env GIT_HTTP_CONNECT_TIMEOUT="10" env GIT_HTTP_USER_AGENT="WPSD-Update (Manual-Update) Ver.# ${dashVer} (${gitBranch}) Call:${CALL} UUID:${uuidStr} [${hwDeetz}] [${osName}]" git --work-tree=${gitFolder} --git-dir=${gitFolder}/.git reset --hard origin/master
+		    fi
 		fi
-               	else
-                	echo -e "${INFO} No updates required for ${gitFolder}."
-	fi
+	    else
+		echo -e "${INFO} No updates required for ${gitFolder}."
+	    fi
 }
 
 main_function() {
@@ -157,39 +157,39 @@ main_function() {
     	pkill slipstream-tasks.sh > /dev/null 2>&1
 
 	if [ -t 1 ] && [[ ${NO_OS} -ne 1 ]]; then
-		# This is running from a terminal, so it should be safe to update the OS
-		echo -e "\nChecking for, and applying any available operating system updates..."
-		apt-get -q=2 update
-		if ! apt-get upgrade --dry-run | grep -qo "0 upgraded" ; then
-		    echo -e "${INFO} Operating system updates available; installing now..."
-		    apt-get upgrade --fix-missing --fix-broken -y
-		    apt-get -q=2 autoremove -y
-		    apt-get -q=2 clean
-		    apt-get -q=2 autoclean
-		else
-		    echo -e "${INFO} No operating system updates required."
+	    # This is running from a terminal, so it should be safe to update the OS
+	    echo -e "\nChecking for, and applying any available operating system updates..."
+	    apt-get -q=2 update
+	    if ! apt-get upgrade --dry-run | grep -qo "0 upgraded" ; then
+		echo -e "${INFO} Operating system updates available; installing now..."
+		apt-get upgrade --fix-missing --fix-broken -y
+		apt-get -q=2 autoremove -y
+		apt-get -q=2 clean
+		apt-get -q=2 autoclean
+	    else
+		echo -e "${INFO} No operating system updates required."
+	    fi
+	    # ensure bullseye has proper php extensions
+	    dpkg --configure -a > /dev/null 2>&1
+	    if [ "${osName}" = "bullseye" ]; then
+		if [ ! -f "/usr/share/php7.4-zip/zip/zip.ini" ] ; then
+		    echo -e "Installing required 'php-zip' package..."
+		    apt-get -q=2 install -y php-zip > /dev/null 2>&1
+		    apt-get -q=2 clean > /dev/null 2<&1
+		    apt-get -q=2 autoclean > /dev/null 2<&1
 		fi
-		# ensure bullseye has proper php extensions
-		dpkg --configure -a > /dev/null 2>&1
-		if [ "${osName}" = "bullseye" ]; then
-		    if [ ! -f "/usr/share/php7.4-zip/zip/zip.ini" ] ; then
-			echo -e "Installing required 'php-zip' package..."
-		        apt-get -q=2 install -y php-zip > /dev/null 2>&1
-		        apt-get -q=2 clean > /dev/null 2<&1
-		        apt-get -q=2 autoclean > /dev/null 2<&1
-		    fi
-		fi
-		echo -e "${TICK} Done!\n"
+	    fi
+	    echo -e "${TICK} Done!\n"
 
-		echo "Checking nginx web server configuration..."
-		if ! [ $(cat /lib/systemd/system/nginx.service | grep -o "mkdir") ]; then
-			sed -i '\/PIDFile=\/run\/nginx.pid/a ExecStartPre=\/bin\/mkdir -p \/var\/log\/nginx' /lib/systemd/system/nginx.service
-			systemctl daemon-reload
-			systemctl restart nginx.service
-			echo "nginx configuration has been updated by operating system; restarting update..."
-			exec "$0" "$@"
-			exit 1
-		fi
+	    echo "Checking nginx web server configuration..."
+	    if ! [ $(cat /lib/systemd/system/nginx.service | grep -o "mkdir") ]; then
+		sed -i '\/PIDFile=\/run\/nginx.pid/a ExecStartPre=\/bin\/mkdir -p \/var\/log\/nginx' /lib/systemd/system/nginx.service
+		systemctl daemon-reload
+		systemctl restart nginx.service
+		echo "nginx configuration has been updated by operating system; restarting update..."
+		exec "$0" "$@"
+		exit 1
+	    fi
 		echo -e "${TICK} Done!"
 	fi
 
@@ -197,16 +197,6 @@ main_function() {
 	echo "Stopping Services..."
 	pistar-services fullstop > /dev/null 2>&1
 	echo -e "${TICK} Done!\n"
-
-	# ensure FS is RW
-	touch /root/.WPSD-updating > /dev/null 2>&1
-	if [ ! -f /root/.WPSD-updating ] ; then
-	    touch /root/.WPSD-updating > /dev/null 2>&1
-	    if [ ! -f /root/.WPSD-updating ] ; then
-		echo -e "Filesystem could not enter R/W mode...please try updating again.\n"
-		exit 1
-	    fi
-	fi
 
 	echo "Updating WPSD Scripts and Support Programs..."
 	git_update /usr/local/sbin
@@ -231,9 +221,9 @@ main_function() {
 	echo "Updating Firewall..."
 	# check if user already has firewall disabled, and if so, ensure it's kept that way.
 	if ! grep -q LOGNDROP /etc/iptables.rules ; then
-        	/usr/local/sbin/pistar-system-manager -dfw > /dev/null 2>&1
+	    /usr/local/sbin/pistar-system-manager -dfw > /dev/null 2>&1
     	else
-        	/usr/local/sbin/pistar-system-manager -efw > /dev/null 2>&1
+	    /usr/local/sbin/pistar-system-manager -efw > /dev/null 2>&1
     	fi
 	echo -e "${TICK} Done!\n"
 
@@ -398,71 +388,71 @@ main_function() {
 
 	# Fix up new P25Gateway Config Hostfile setup
 	if [ ! -f /root/P25Hosts.txt ]; then
-		touch /root/P25Hosts.txt
+	    touch /root/P25Hosts.txt
 	fi
 
 	# Fix up new NXDNGateway Config Hostfile setup
 	if [ ! -f /root/NXDNHosts.txt ]; then
-		touch /root/NXDNHosts.txt
+	    touch /root/NXDNHosts.txt
 	fi
 	if [ ! -f /usr/local/etc/NXDNHostsLocal.txt ]; then
-		touch /usr/local/etc/NXDNHostsLocal.txt
+	    touch /usr/local/etc/NXDNHostsLocal.txt
 	fi
 
 	# Download M17 Audio files if missing
 	if [[ ! -d /usr/local/etc/M17_Audio ]]; then
-		mkdir -p /usr/local/etc/M17_Audio/
-        	curl --fail -o /usr/local/etc/M17_Audio/de_DE.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/de_DE.m17
-        	curl --fail -o /usr/local/etc/M17_Audio/de_DE.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/de_DE.indx
-        	curl --fail -o /usr/local/etc/M17_Audio/dk_DK.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/dk_DK.m17
-        	curl --fail -o /usr/local/etc/M17_Audio/dk_DK.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/dk_DK.indx
-        	curl --fail -o /usr/local/etc/M17_Audio/en_GB.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/en_GB.m17
-        	curl --fail -o /usr/local/etc/M17_Audio/en_GB.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/en_GB.indx
-        	curl --fail -o /usr/local/etc/M17_Audio/en_US.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/en_US.m17
-        	curl --fail -o /usr/local/etc/M17_Audio/en_US.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/en_US.indx
-       		curl --fail -o /usr/local/etc/M17_Audio/es_ES.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/es_ES.m17
-        	curl --fail -o /usr/local/etc/M17_Audio/es_ES.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/es_ES.indx
-        	curl --fail -o /usr/local/etc/M17_Audio/fr_FR.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/fr_FR.m17
-        	curl --fail -o /usr/local/etc/M17_Audio/fr_FR.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/fr_FR.indx
-        	curl --fail -o /usr/local/etc/M17_Audio/it_IT.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/it_IT.m17
-        	curl --fail -o /usr/local/etc/M17_Audio/it_IT.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/it_IT.indx
-        	curl --fail -o /usr/local/etc/M17_Audio/pl_PL.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/pl_PL.m17
-        	curl --fail -o /usr/local/etc/M17_Audio/pl_PL.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/pl_PL.indx
-        	curl --fail -o /usr/local/etc/M17_Audio/se_SE.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/se_SE.m17
-        	curl --fail -o /usr/local/etc/M17_Audio/se_SE.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/se_SE.indx    
+	    mkdir -p /usr/local/etc/M17_Audio/
+	    curl --fail -o /usr/local/etc/M17_Audio/de_DE.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/de_DE.m17
+	    curl --fail -o /usr/local/etc/M17_Audio/de_DE.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/de_DE.indx
+	    curl --fail -o /usr/local/etc/M17_Audio/dk_DK.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/dk_DK.m17
+	    curl --fail -o /usr/local/etc/M17_Audio/dk_DK.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/dk_DK.indx
+	    curl --fail -o /usr/local/etc/M17_Audio/en_GB.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/en_GB.m17
+	    curl --fail -o /usr/local/etc/M17_Audio/en_GB.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/en_GB.indx
+	    curl --fail -o /usr/local/etc/M17_Audio/en_US.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/en_US.m17
+	    curl --fail -o /usr/local/etc/M17_Audio/en_US.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/en_US.indx
+	    curl --fail -o /usr/local/etc/M17_Audio/es_ES.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/es_ES.m17
+	    curl --fail -o /usr/local/etc/M17_Audio/es_ES.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/es_ES.indx
+	    curl --fail -o /usr/local/etc/M17_Audio/fr_FR.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/fr_FR.m17
+	    curl --fail -o /usr/local/etc/M17_Audio/fr_FR.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/fr_FR.indx
+	    curl --fail -o /usr/local/etc/M17_Audio/it_IT.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/it_IT.m17
+	    curl --fail -o /usr/local/etc/M17_Audio/it_IT.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/it_IT.indx
+	    curl --fail -o /usr/local/etc/M17_Audio/pl_PL.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/pl_PL.m17
+	    curl --fail -o /usr/local/etc/M17_Audio/pl_PL.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/pl_PL.indx
+	    curl --fail -o /usr/local/etc/M17_Audio/se_SE.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/se_SE.m17
+	    curl --fail -o /usr/local/etc/M17_Audio/se_SE.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/se_SE.indx    
     	fi
 
 	# Add Portuguese voice files for DMRGateway and ircDDBGw if missing
 	if [[ ! -f /usr/local/etc/DMR_Audio/pt_PT.ambe ]]; then
-		curl --fail -o /usr/local/etc/DMR_Audio/pt_PT.ambe -s https://raw.githubusercontent.com/g4klx/DMRGateway/master/Audio/pt_PT.ambe
-		curl --fail -o /usr/local/etc/DMR_Audio/pt_PT.indx -s https://raw.githubusercontent.com/g4klx/DMRGateway/master/Audio/pt_PT.indx
-		chmod 664 /usr/local/etc/DMR_Audio/*.ambe
-		chmod 664 /usr/local/etc/DMR_Audio/*.indx
+	    curl --fail -o /usr/local/etc/DMR_Audio/pt_PT.ambe -s https://raw.githubusercontent.com/g4klx/DMRGateway/master/Audio/pt_PT.ambe
+	    curl --fail -o /usr/local/etc/DMR_Audio/pt_PT.indx -s https://raw.githubusercontent.com/g4klx/DMRGateway/master/Audio/pt_PT.indx
+	    chmod 664 /usr/local/etc/DMR_Audio/*.ambe
+	    chmod 664 /usr/local/etc/DMR_Audio/*.indx
 	fi
 	if [[ ! -f /usr/local/etc/ircddbgateway/pt_PT.ambe ]]; then
-		curl --fail -o /usr/local/etc/ircddbgateway/pt_PT.ambe -s https://raw.githubusercontent.com/g4klx/ircDDBGateway/master/Data/pt_PT.ambe
-		curl --fail -o /usr/local/etc/ircddbgateway/pt_PT.indx -s https://raw.githubusercontent.com/g4klx/ircDDBGateway/master/Data/pt_PT.indx
-		curl --fail -o /usr/local/etc/ircddbgateway/TIME_pt_PT.ambe -s https://raw.githubusercontent.com/g4klx/ircDDBGateway/master/Data/TIME_pt_PT.ambe
-		curl --fail -o /usr/local/etc/ircddbgateway/TIME_pt_PT.indx -s https://raw.githubusercontent.com/g4klx/ircDDBGateway/master/Data/TIME_pt_PT.indx
-		chmod 664 /usr/local/etc/ircddbgateway/*.ambe
-		chmod 664 /usr/local/etc/ircddbgateway/*.indx
+	    curl --fail -o /usr/local/etc/ircddbgateway/pt_PT.ambe -s https://raw.githubusercontent.com/g4klx/ircDDBGateway/master/Data/pt_PT.ambe
+	    curl --fail -o /usr/local/etc/ircddbgateway/pt_PT.indx -s https://raw.githubusercontent.com/g4klx/ircDDBGateway/master/Data/pt_PT.indx
+	    curl --fail -o /usr/local/etc/ircddbgateway/TIME_pt_PT.ambe -s https://raw.githubusercontent.com/g4klx/ircDDBGateway/master/Data/TIME_pt_PT.ambe
+	    curl --fail -o /usr/local/etc/ircddbgateway/TIME_pt_PT.indx -s https://raw.githubusercontent.com/g4klx/ircDDBGateway/master/Data/TIME_pt_PT.indx
+	    chmod 664 /usr/local/etc/ircddbgateway/*.ambe
+	    chmod 664 /usr/local/etc/ircddbgateway/*.indx
 	fi
 	
 	if [[ $(grep "\[Voice\]" /etc/p25gateway | wc -l) -eq 0 ]]; then
-		echo "" >> /etc/p25gateway
-		sed -i '$a[Voice]\nEnabled=1\nLanguage=en_GB\nDirectory=/usr/local/etc/P25_Audio\n' /etc/p25gateway
+	    echo "" >> /etc/p25gateway
+	    sed -i '$a[Voice]\nEnabled=1\nLanguage=en_GB\nDirectory=/usr/local/etc/P25_Audio\n' /etc/p25gateway
 	fi
 
         if [ -f /usr/local/bin/platformDetect.sh ]; then # remove platformDetect.sh since we have a custom version in /usr/local/sbin
-		rm -f /usr/local/bin/platformDetect.sh
+	    rm -f /usr/local/bin/platformDetect.sh
         fi
 
 	if ! grep -q TIME_FORMAT /var/www/dashboard/config/config.php ; then # insert req'd constant if not found. WIll be stashed on next update :-)
-		sed -i "/^date_default_timezone_set.*/i define('TIME_FORMAT', '24');" /var/www/dashboard/config/config.php
+	    sed -i "/^date_default_timezone_set.*/i define('TIME_FORMAT', '24');" /var/www/dashboard/config/config.php
 	fi
 
 	if ! grep -q AUTO_UPDATE_CHECK /var/www/dashboard/config/config.php ; then # insert req'd constant if not found. WIll be stashed on next update :-)
-		sed -i "/^date_default_timezone_set.*/i define('AUTO_UPDATE_CHECK', 'true');" /var/www/dashboard/config/config.php
+	    sed -i "/^date_default_timezone_set.*/i define('AUTO_UPDATE_CHECK', 'true');" /var/www/dashboard/config/config.php
 	fi
 
 	# MOTD
@@ -471,22 +461,22 @@ main_function() {
 	# Add pistar-service bash completion if missing
 	DEST="/usr/share/bash-completion/completions/pistar-services"
 	if [ ! -f $DEST ] ; then
-		echo "#!/bin/bash" > $DEST
-		echo "" >> $DEST
-		echo "_pistar_services()" >> $DEST
-		echo "{" >> $DEST
-		echo "    local cur prev words cword" >> $DEST
-		echo "    _init_completion -n = || return" >> $DEST
-		echo "" >> $DEST
-		echo "    _expand || return 0" >> $DEST
-		echo "" >> $DEST
-		echo "    COMPREPLY=( \$( compgen -W 'start stop restart fullstop status' -- \"\$cur\" ) )" >> $DEST
-		echo "" >> $DEST
-		echo "} &&" >> $DEST
-		echo "complete -F _pistar_services pistar-services" >> $DEST
-		echo "" >> $DEST
-		chown root:root $DEST
-		chmod 0644 $DEST
+	    echo "#!/bin/bash" > $DEST
+	    echo "" >> $DEST
+	    echo "_pistar_services()" >> $DEST
+	    echo "{" >> $DEST
+	    echo "    local cur prev words cword" >> $DEST
+	    echo "    _init_completion -n = || return" >> $DEST
+	    echo "" >> $DEST
+	    echo "    _expand || return 0" >> $DEST
+	    echo "" >> $DEST
+	    echo "    COMPREPLY=( \$( compgen -W 'start stop restart fullstop status' -- \"\$cur\" ) )" >> $DEST
+	    echo "" >> $DEST
+	    echo "} &&" >> $DEST
+	    echo "complete -F _pistar_services pistar-services" >> $DEST
+	    echo "" >> $DEST
+	    chown root:root $DEST
+	    chmod 0644 $DEST
 	fi
 
 	# Get and cache latest W0CHP-PiStar-Dash version from remote Git repo:
@@ -510,23 +500,23 @@ main_function() {
 	echo -e "${TICK} Done!\n"
 
 	echo "Updates complete, syncing disk cache..."
-	rm /root/.WPSD-updating > /dev/null 2>&1
 	/bin/sync
 	/bin/sync
 	/bin/sync
 	systemctl start cron.service > /dev/null 2<&1
 	echo -e "${TICK} Update Process Finished!\n"
 	if [ ! -t 1 ]; then # only output if not called from tty
-		echo -e "\n<b><a style='color:white;text-decoration:underline;'' href='/'>Back to Dashboard...</a></b>\n"
+	    echo -e "\n<b><a style='color:white;text-decoration:underline;'' href='/'>Back to Dashboard...</a></b>\n"
 	fi
 }
 
 	if [ -t 1 ]; then
- 		# run via terminal, only output to screen
- 		main_function
+ 	    # run via terminal, only output to screen
+ 	    main_function
 	else
- 		# if not run via terminal, log everything into a log file
- 		main_function >> /var/log/pi-star/WPSD-update.log 2>&1
+ 	    # if not run via terminal, log everything into a log file
+ 	    main_function >> /var/log/pi-star/WPSD-update.log 2>&1
 	fi
 
 exit 0
+
