* Minor: clean & rename deprecated cmds.

diff --git a/pistar-mmdvmcal b/pistar-mmdvmcal
--- a/pistar-mmdvmcal
+++ b/pistar-mmdvmcal
@@ -1,53 +1,23 @@
 #!/bin/bash
-#
-##############################################################################
-#                                                                            #
-#                          Pi-Star MMDVMCal Tool                             #
-#                                                                            #
-#     Version 1.1, Code, Design and Development by Andy Taylor (MW0MWZ).     #
-#                                                                            #
-#                 Make it simple to run MMDVMCal on Pi-Star.                 #
-#                      Orrigional suggestion by "mrickey"                    #
-#                                                                            #
-##############################################################################
-#
-if [ "$(id -u)" != "0" ]; then
-  echo -e "You need to be root to run this command...\n"
-  exit 1
-fi
 
-# Get the modem port from /etc/mmdvmhost
-mmdvmModem=$(grep -m 1 'Port=' /etc/mmdvmhost | awk -F "=" '/Port/ {print $2}')
-modemSpeed=$(grep -m 1 'UARTSpeed=' /etc/mmdvmhost | awk -F "=" '/UARTSpeed/ {print $2}')
+source /usr/local/sbin/.wpsd-shell-funcs
 
-# Output some feedback to the terminal
-echo "Stopping Services..."
+script_name=$(basename "$0")
 
-# Stop the services
-systemctl stop pistar-watchdog.timer >/dev/null 2>&1
-systemctl stop pistar-watchdog.service >/dev/null 2>&1
-systemctl stop mmdvmhost.timer
-systemctl stop mmdvmhost.service
+clear
+echo -e "\n${NOTE} ${COL_LIGHT_YELLOW}Note:${COL_NC} The old command '$script_name' is deprecated. Please use 'wpsd-modemcalibrate' instead."
 
-# Force Kill any remaining MMDVMHost processes
-echo "Stopping any remaining MMDVMHost processes..."
-killall MMDVMHost >/dev/null 2>&1
-killall MMDVMHost_NoOLED >/dev/null 2>&1
-killall MMDVMHost_Adafruit >/dev/null 2>&1
+echo -e "\nI'll run the command for you in 10 seconds...\n"
 
-# Output some feedback to the terminal
-echo "Starting Calibration..."
+for ((i=10; i>=1; i--)); do
+  printf "\r${INFO} Starting in $i seconds... Press 'q' to abort "
+  if [[ -t 0 ]]; then
+    read -t 1 -n 1 key
+    if [[ $key == "q" || $key == "Q" ]]; then
+      printf "\nAborted by user\n"
+      exit 1
+    fi
+  fi
+done
 
-/usr/local/bin/MMDVMCal ${modemSpeed} ${mmdvmModem}
-
-# Output some feedback to the terminal
-echo "Starting Services..."
-
-# Start the services
-systemctl start pistar-watchdog.timer >/dev/null 2>&1
-systemctl start pistar-watchdog >/dev/null 2>&1
-systemctl start mmdvmhost.timer
-systemctl start mmdvmhost
-
-# Complete
-echo "Finished..."
+exec env /usr/local/sbin/wpsd-modemcalibrate
